# -*- coding: utf-8 -*-
"""arbol_avl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_5GfSnAg-46Hmhlfp45O_4mgUZQK38Y
"""

"""Módulo de implementación de un Árbol Binario Auto-balanceado (AVL)."""


class NodoAVL:
    """Representa un nodo dentro del árbol AVL con altura y referencias."""

    def __init__(self, valor):
        self._valor = valor
        self._izquierdo = None
        self._derecho = None
        self._altura = 1

    @property
    def valor(self):
        return self._valor

    @valor.setter
    def valor(self, nuevo_valor):
        self._valor = nuevo_valor

    @property
    def izquierdo(self):
        return self._izquierdo

    @izquierdo.setter
    def izquierdo(self, nodo):
        self._izquierdo = nodo

    @property
    def derecho(self):
        return self._derecho

    @derecho.setter
    def derecho(self, nodo):
        self._derecho = nodo

    @property
    def altura(self):
        return self._altura

    @altura.setter
    def altura(self, nueva_altura):
        self._altura = nueva_altura


class ArbolAVL:
    """Implementación de la estructura de datos Árbol AVL."""

    def __init__(self):
        self._raiz = None

    @property
    def raiz(self):
        return self._raiz

    def es_vacio(self):
        """Comprueba si el árbol carece de raíz."""
        return self._raiz is None

    def _obtener_altura(self, nodo):
        if nodo is None:
            return 0
        return nodo.altura

    def _factor_equilibrio(self, nodo):
        if nodo is None:
            return 0
        return self._obtener_altura(nodo.derecho) - self._obtener_altura(nodo.izquierdo)

    def _rotacion_derecha(self, y):
        x = y.izquierdo
        t2 = x.derecho

        # Efectuar rotación
        x.derecho = y
        y.izquierdo = t2

        # Actualizar alturas
        y.altura = 1 + max(self._obtener_altura(y.izquierdo), self._obtener_altura(y.derecho))
        x.altura = 1 + max(self._obtener_altura(x.izquierdo), self._obtener_altura(x.derecho))

        return x

    def _rotacion_izquierda(self, x):
        y = x.derecho
        t2 = y.izquierdo

        # Efectuar rotación
        y.izquierdo = x
        x.derecho = t2

        # Actualizar alturas
        x.altura = 1 + max(self._obtener_altura(x.izquierdo), self._obtener_altura(x.derecho))
        y.altura = 1 + max(self._obtener_altura(y.izquierdo), self._obtener_altura(y.derecho))

        return y

    def insertar(self, valor):
        """Inserta un valor en el árbol balanceándolo automáticamente."""
        self._raiz = self._insertar_recursivo(self._raiz, valor)

    def _insertar_recursivo(self, nodo, valor):
        # 1. Inserción normal de BST
        if nodo is None:
            return NodoAVL(valor)

        if valor < nodo.valor:
            nodo.izquierdo = self._insertar_recursivo(nodo.izquierdo, valor)
        elif valor > nodo.valor:
            nodo.derecho = self._insertar_recursivo(nodo.derecho, valor)
        else:
            return nodo  # Duplicados no permitidos

        # 2. Actualizar altura del nodo ancestro
        nodo.altura = 1 + max(self._obtener_altura(nodo.izquierdo), self._obtener_altura(nodo.derecho))

        # 3. Obtener el factor de equilibrio
        balance = self._factor_equilibrio(nodo)

        # 4. Aplicar rotaciones según los 4 casos posibles

        # Caso Izquierda - Izquierda (LL)
        if balance < -1 and valor < nodo.izquierdo.valor:
            return self._rotacion_derecha(nodo)

        # Caso Derecha - Derecha (RR)
        if balance > 1 and valor > nodo.derecho.valor:
            return self._rotacion_izquierda(nodo)

        # Caso Izquierda - Derecha (LR)
        if balance < -1 and valor > nodo.izquierdo.valor:
            nodo.izquierdo = self._rotacion_izquierda(nodo.izquierdo)
            return self._rotacion_derecha(nodo)

        # Caso Derecha - Izquierda (RL)
        if balance > 1 and valor < nodo.derecho.valor:
            nodo.derecho = self._rotacion_derecha(nodo.derecho)
            return self._rotacion_izquierda(nodo)

        return nodo

    def in_orden(self):
        """Recorrido in-orden para comprobar elementos ordenados."""
        elementos = []
        self._in_orden_recursivo(self._raiz, elementos)
        return elementos

    def _in_orden_recursivo(self, nodo, elementos):
        if nodo is not None:
            self._in_orden_recursivo(nodo.izquierdo, elementos)
            elementos.append(nodo.valor)
            self._in_orden_recursivo(nodo.derecho, elementos)

    def imprimir_arbol(self, nodo=None, nivel=0, prefijo="Raíz: "):
        """Imprime la estructura jerárquica del árbol con factores de balance."""
        if nodo is None and nivel == 0:
            nodo = self._raiz

        if nodo is not None:
            print(" " * (nivel * 4) + prefijo + f"{nodo.valor} (FE: {self._factor_equilibrio(nodo)})")
            if nodo.izquierdo or nodo.derecho:
                if nodo.izquierdo:
                    self.imprimir_arbol(nodo.izquierdo, nivel + 1, "Izq: ")
                if nodo.derecho:
                    self.imprimir_arbol(nodo.derecho, nivel + 1, "Der: ")


if __name__ == "__main__":
    arbol = ArbolAVL()
    # Inserción en orden estrictamente creciente (provocaría desbalance en un BST tradicional)
    claves = [10, 20, 30, 40, 50, 25]

    for clave in claves:
        arbol.insertar(clave)

    print("--- Estructura del Árbol AVL Balanceado ---")
    arbol.imprimir_arbol()
    print("\nRecorrido In-Orden:", arbol.in_orden())