# -*- coding: utf-8 -*-
"""Árbol_Binario_de_Expresiones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HugrcnRJTKNp0O9BAHO-BMIoL7NSM-ok
"""

class NodoExpresion:
    def __init__(self, valor):
        self.valor = valor
        self.izquierdo = None
        self.derecho = None

    def EsHoja(self):
        """Devuelve True si el nodo no tiene hijos (es un operando)."""
        return self.izquierdo is None and self.derecho is None


class ArbolExpresiones:
    def __init__(self):
        self.raiz = None

    def EsVacio(self):
        """Comprueba si el árbol está vacío."""
        return self.raiz is None

    def es_operador(self, c):
        return c in ['+', '-', '*', '/', '^']

    def precedencia(self, op):
        if op == '^':
            return 3
        if op in ['*', '/']:
            return 2
        if op in ['+', '-']:
            return 1
        return 0

    def infija_a_posfija(self, expresion):
        """Convierte una expresión infija a posfija con Shunting Yard."""
        pila = []
        salida = []

        expresion_formateada = expresion.replace('(', ' ( ').replace(')', ' ) ')
        for op in ['+', '-', '*', '/', '^']:
            expresion_formateada = expresion_formateada.replace(op, f' {op} ')

        tokens = expresion_formateada.split()

        for token in tokens:
            if token.isalnum():
                salida.append(token)
            elif token == '(':
                pila.append(token)
            elif token == ')':
                while pila and pila[-1] != '(':
                    salida.append(pila.pop())
                if pila and pila[-1] == '(':
                    pila.pop()
            elif self.es_operador(token):
                while (pila and pila[-1] != '(' and
                       self.precedencia(pila[-1]) >= self.precedencia(token)):
                    salida.append(pila.pop())
                pila.append(token)

        while pila:
            salida.append(pila.pop())

        return salida

    def InsertarNodo(self, x):
        """Construye el árbol a partir de la expresión infija o token."""
        if isinstance(x, str) and any(op in x for op in ['+', '-', '*', '/', '^', ' ']):
            tokens = self.infija_a_posfija(x)
            self.construir_arbol(tokens)
        else:
            if self.raiz is None:
                self.raiz = NodoExpresion(x)

    def construir_arbol(self, tokens_posfija):
        """Construye el árbol a partir de tokens en posfija."""
        pila = []
        for token in tokens_posfija:
            if not self.es_operador(token):
                pila.append(NodoExpresion(token))
            else:
                nodo = NodoExpresion(token)
                nodo.derecho = pila.pop()
                nodo.izquierdo = pila.pop()
                pila.append(nodo)

        if pila:
            self.raiz = pila.pop()

    def BuscarX(self, x, nodo=None):
        """Busca si un elemento x existe en el árbol."""
        if nodo is None:
            if self.raiz is None:
                return False
            nodo = self.raiz

        if nodo.valor == str(x):
            return True

        izq = self.BuscarX(x, nodo.izquierdo) if nodo.izquierdo else False
        der = self.BuscarX(x, nodo.derecho) if nodo.derecho else False
        return izq or der

    def PreOrden(self, nodo=None):
        """Recorrido Pre-Orden (Notación Prefija)."""
        if nodo is None:
            if self.raiz is None:
                return []
            nodo = self.raiz

        res = [nodo.valor]
        if nodo.izquierdo:
            res.extend(self.PreOrden(nodo.izquierdo))
        if nodo.derecho:
            res.extend(self.PreOrden(nodo.derecho))
        return res

    def InOrden(self, nodo=None):
        """Recorrido In-Orden (Notación Infija)."""
        if nodo is None:
            if self.raiz is None:
                return []
            nodo = self.raiz

        res = []
        if nodo.izquierdo:
            res.extend(self.InOrden(nodo.izquierdo))
        res.append(nodo.valor)
        if nodo.derecho:
            res.extend(self.InOrden(nodo.derecho))
        return res

    def PostOrden(self, nodo=None):
        """Recorrido Post-Orden (Notación Posfija)."""
        if nodo is None:
            if self.raiz is None:
                return []
            nodo = self.raiz

        izq = self.PostOrden(nodo.izquierdo) if nodo.izquierdo else []
        der = self.PostOrden(nodo.derecho) if nodo.derecho else []
        return izq + der + [nodo.valor]


def main():
    print("--- Práctica: Árbol de Expresiones ---")
    expresion_infija = input("Introduce una expresión matemática infija (ej. (A + B) * C): ")

    arbol = ArbolExpresiones()

    # Construcción mediante InsertarNodo
    arbol.InsertarNodo(expresion_infija)
    print("\n[INFO] Árbol de expresiones construido con éxito.")

    # Verificación de métodos requeridos
    print(f"¿Árbol vacío?: {arbol.EsVacio()}")
    print(f"¿La raíz es hoja?: {arbol.raiz.EsHoja()}")
    print(f"Búsqueda de elemento 'A': {arbol.BuscarX('A')}")

    # Recorridos
    print(f"\n=> Posfija (PostOrden) : {' '.join(arbol.PostOrden())}")
    print(f"=> Infija  (InOrden)   : {' '.join(arbol.InOrden())}")
    print(f"=> Prefija (PreOrden)  : {' '.join(arbol.PreOrden())}")


if __name__ == "__main__":
    main()