# -*- coding: utf-8 -*-
"""Arbol_ADT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHzwdpuAMxCymmyqFs7iSxgMNPn0kGhj
"""

from collections import deque


class Nodo:
    """Clase que representa un nodo dentro de un árbol binario."""

    def __init__(self, valor):
        self._valor = valor
        self._izquierdo = None
        self._derecho = None

    @property
    def valor(self):
        return self._valor

    @valor.setter
    def valor(self, nuevo_valor):
        self._valor = nuevo_valor

    @property
    def izquierdo(self):
        return self._izquierdo

    @izquierdo.setter
    def izquierdo(self, nodo):
        self._izquierdo = nodo

    @property
    def derecho(self):
        return self._derecho

    @derecho.setter
    def derecho(self, nodo):
        self._derecho = nodo

    def EsHoja(self):
        """Verifica si el nodo actual no tiene descendientes."""
        return self._izquierdo is None and self._derecho is None


class ArbolBinario:
    """Estructura de datos abstracta que modela un Árbol Binario."""

    def __init__(self):
        self._raiz = None

    @property
    def raiz(self):
        return self._raiz

    @raiz.setter
    def raiz(self, nodo):
        self._raiz = nodo

    def EsVacio(self):
        """Indica si el árbol carece de raíz."""
        return self._raiz is None

    def Insertar(self, valor):
        """Inserta un nuevo valor en el árbol respetando el orden BST."""
        if self.EsVacio():
            self._raiz = Nodo(valor)
        else:
            self._insertar_recursivo(self._raiz, valor)

    def _insertar_recursivo(self, nodo_actual, valor):
        if valor < nodo_actual.valor:
            if nodo_actual.izquierdo is None:
                nodo_actual.izquierdo = Nodo(valor)
            else:
                self._insertar_recursivo(nodo_actual.izquierdo, valor)
        elif valor > nodo_actual.valor:
            if nodo_actual.derecho is None:
                nodo_actual.derecho = Nodo(valor)
            else:
                self._insertar_recursivo(nodo_actual.derecho, valor)

    def Buscar(self, valor):
        """Busca si un elemento existe dentro del árbol."""
        return self._buscar_recursivo(self._raiz, valor)

    def _buscar_recursivo(self, nodo_actual, valor):
        if nodo_actual is None:
            return False
        if nodo_actual.valor == valor:
            return True
        if valor < nodo_actual.valor:
            return self._buscar_recursivo(nodo_actual.izquierdo, valor)
        return self._buscar_recursivo(nodo_actual.derecho, valor)

    def EsHoja(self, valor):
        """Busca un nodo por su valor y determina si es hoja."""
        nodo = self._obtener_nodo(self._raiz, valor)
        if nodo is not None:
            return nodo.EsHoja()
        return False

    def _obtener_nodo(self, nodo_actual, valor):
        if nodo_actual is None or nodo_actual.valor == valor:
            return nodo_actual
        if valor < nodo_actual.valor:
            return self._obtener_nodo(nodo_actual.izquierdo, valor)
        return self._obtener_nodo(nodo_actual.derecho, valor)

    def Altura(self):
        """Calcula la altura máxima del árbol (número de niveles)."""
        return self._altura_recursivo(self._raiz)

    def _altura_recursivo(self, nodo):
        if nodo is None:
            return 0
        altura_izq = self._altura_recursivo(nodo.izquierdo)
        altura_der = self._altura_recursivo(nodo.derecho)
        return 1 + max(altura_izq, altura_der)

    def Cantidad(self):
        """Retorna el número total de nodos presentes en el árbol."""
        return self._cantidad_recursivo(self._raiz)

    def _cantidad_recursivo(self, nodo):
        if nodo is None:
            return 0
        return 1 + self._cantidad_recursivo(nodo.izquierdo) + self._cantidad_recursivo(nodo.derecho)

    def Amplitud(self):
        """Realiza el recorrido por niveles (BFS) y devuelve los valores en orden."""
        if self.EsVacio():
            return []

        resultado = []
        cola = deque([self._raiz])

        while cola:
            nodo_actual = cola.popleft()
            resultado.append(nodo_actual.valor)

            if nodo_actual.izquierdo is not None:
                cola.append(nodo_actual.izquierdo)
            if nodo_actual.derecho is not None:
                cola.append(nodo_actual.derecho)

        return resultado


if __name__ == "__main__":
    arbol = ArbolBinario()

    # Inserción de valores de prueba
    valores = [50, 30, 70, 20, 40, 60, 80]
    for val in valores:
        arbol.Insertar(val)

    # Verificación de operaciones
    print("Recorrido por Amplitud:", arbol.Amplitud())
    print("Cantidad de nodos:", arbol.Cantidad())
    print("Altura del árbol:", arbol.Altura())
    print("¿Existe el 40?:", arbol.Buscar(40))
    print("¿Existe el 99?:", arbol.Buscar(99))
    print("¿El nodo 20 es hoja?:", arbol.EsHoja(20))
    print("¿El nodo 30 es hoja?:", arbol.EsHoja(30))